import AppKit
import Foundation
import Observation

// Polls NSPasteboard.general every 500ms and captures new clipboard content
@MainActor @Observable
final class ClipboardMonitor {
    private let store: ClipboardStore
    private var timer: Timer?
    private var lastChangeCount: Int = 0

    // Pasteboard types to ignore (passwords, auto-generated)
    private let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-password-field",
    ]

    init(store: ClipboardStore) {
        self.store = store
        lastChangeCount = NSPasteboard.general.changeCount
        startMonitoring()
    }

    func startMonitoring() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(
            withTimeInterval: 0.5, repeats: true
        ) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    // Sync lastChangeCount after a self-triggered write to skip it
    func syncChangeCount() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func checkClipboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        // Check for concealed/password types
        let types = pb.types ?? []
        let typeStrings = types.map { $0.rawValue }
        if typeStrings.contains(where: { concealedTypes.contains($0) }) {
            return
        }

        // Try to capture content by priority
        if let item = captureClipboardContent(from: pb) {
            store.add(item)
        }
    }

    private func captureClipboardContent(
        from pb: NSPasteboard
    ) -> ClipboardItem? {
        // Priority: image > fileURL > rtf > html > text
        if let imageItem = captureImage(from: pb) { return imageItem }
        if let fileItem = captureFileURLs(from: pb) { return fileItem }
        if let rtfItem = captureRTF(from: pb) { return rtfItem }
        if let htmlItem = captureHTML(from: pb) { return htmlItem }
        if let textItem = captureText(from: pb) { return textItem }
        return nil
    }

    private func captureImage(from pb: NSPasteboard) -> ClipboardItem? {
        guard let imageData = pb.data(forType: .png)
            ?? pb.data(forType: .tiff)
        else { return nil }

        // Compress image: resize if > 1MB, generate thumbnail
        let (compressed, thumbnail) = compressImageData(imageData)

        return ClipboardItem(
            id: UUID(), timestamp: Date(), contentType: .image,
            textContent: nil, imageData: compressed,
            thumbnailData: thumbnail, rtfData: nil,
            htmlContent: nil, fileURLs: nil)
    }

    private func captureFileURLs(from pb: NSPasteboard) -> ClipboardItem? {
        guard let urls = pb.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty else { return nil }

        return ClipboardItem(
            id: UUID(), timestamp: Date(), contentType: .fileURL,
            textContent: nil, imageData: nil, thumbnailData: nil,
            rtfData: nil, htmlContent: nil, fileURLs: urls)
    }

    private func captureRTF(from pb: NSPasteboard) -> ClipboardItem? {
        guard let rtfData = pb.data(forType: .rtf) else { return nil }
        // Also grab plain text if available for search
        let plainText = pb.string(forType: .string)

        return ClipboardItem(
            id: UUID(), timestamp: Date(), contentType: .rtf,
            textContent: plainText, imageData: nil, thumbnailData: nil,
            rtfData: rtfData, htmlContent: nil, fileURLs: nil)
    }

    private func captureHTML(from pb: NSPasteboard) -> ClipboardItem? {
        guard let htmlString = pb.string(forType: .html) else { return nil }
        let plainText = pb.string(forType: .string)

        return ClipboardItem(
            id: UUID(), timestamp: Date(), contentType: .html,
            textContent: plainText, imageData: nil, thumbnailData: nil,
            rtfData: nil, htmlContent: htmlString, fileURLs: nil)
    }

    private func captureText(from pb: NSPasteboard) -> ClipboardItem? {
        guard let text = pb.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }

        return ClipboardItem(
            id: UUID(), timestamp: Date(), contentType: .text,
            textContent: text, imageData: nil, thumbnailData: nil,
            rtfData: nil, htmlContent: nil, fileURLs: nil)
    }

    // Compress large images and generate thumbnail
    private func compressImageData(_ data: Data) -> (Data, Data?) {
        guard let image = NSImage(data: data) else {
            return (data, nil)
        }

        let maxDimension: CGFloat = 1024
        let thumbnailSize: CGFloat = 200
        let size = image.size

        // Generate thumbnail
        let thumbScale = min(
            thumbnailSize / size.width, thumbnailSize / size.height, 1.0)
        let thumbSize = NSSize(
            width: size.width * thumbScale,
            height: size.height * thumbScale)
        let thumbnail = resizeAndCompress(
            image: image, targetSize: thumbSize, quality: 0.6)

        // Compress full image if > 1MB
        if data.count > 1_000_000 {
            let scale = min(
                maxDimension / size.width, maxDimension / size.height, 1.0)
            let newSize = NSSize(
                width: size.width * scale, height: size.height * scale)
            let compressed = resizeAndCompress(
                image: image, targetSize: newSize, quality: 0.7)
            return (compressed ?? data, thumbnail)
        }

        return (data, thumbnail)
    }

    private func resizeAndCompress(
        image: NSImage, targetSize: NSSize, quality: CGFloat
    ) -> Data? {
        // Use CGContext instead of deprecated lockFocus/unlockFocus
        let width = Int(targetSize.width)
        let height = Int(targetSize.height)
        guard let bitmapRep = NSBitmapImageRep(
            bitmapDataPlanes: nil, pixelsWide: width, pixelsHigh: height,
            bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
            isPlanar: false, colorSpaceName: .deviceRGB,
            bytesPerRow: 0, bitsPerPixel: 0
        ) else { return nil }

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: bitmapRep)
        image.draw(
            in: NSRect(origin: .zero, size: targetSize),
            from: NSRect(origin: .zero, size: image.size),
            operation: .copy, fraction: 1.0)
        NSGraphicsContext.restoreGraphicsState()

        return bitmapRep.representation(
            using: .jpeg, properties: [.compressionFactor: quality])
    }
}
